* Formal Experiment

In January 2011, a formal experiment was conducted which aimed to
clear some questions in the field of personal information management
(PIM), information re-finding, and information architecture. This
repository holds relevant data to verify or extend this experiment.

For this purpose, the testing framework tagstore ([[http://tagstore.org]])
was used to *compare* storing files (images, graphics and documents)
within the *folder hierarchy* using Microsoft Windows Explorer *and
tagstore*.

The tagstore framework supports file management by applying
tags. Those tags are being used to (automatically) generate *navigation
hierarchies*, called TagTrees.

This repository contains anonymous data from the experiment in order
to *check, extend, or re-evaluate the experiment*.

This is Open Data.

This is [[http://en.wikipedia.org/wiki/Open_research][Open Science]].

* Other Experiment Repositories

In April 2011, we basically repeated the January-experiment. The April
experiment has less technical logs, a two week pause between filing
and re-finding, more test persons, more test items, more detailed
questionnaires:
https://github.com/novoid/2011-04-tagstore-formal-experiment

* Language

The experiment was conducted by a group of Karl Voit ([[http://www.TUGraz.az][Graz University
of Technology]]) and took place in [[http://maps.google.com/maps?f%3Dq&source%3Ds_q&hl%3Den&geocode%3D&q%3DInffeldgasse%2B16b,%2Bgraz,%2Baustria&aq%3D&sll%3D47.070714,15.439504&sspn%3D0.143575,0.308647&vpsrc%3D0&ie%3DUTF8&hq%3D&hnear%3DInffeldgasse%2B16b,%2BJakomini%2B8010%2BGraz,%2BSteiermark,%2BAustria&t%3Dh&z%3D16&iwloc%3DA][Graz, Austria]]. Therefore, the
language of the test persons was *German*. All data which test persons
were confronted with is in German. Derived data and supplementary
things such as evaluation scripts are in *English* though.

* White Papers

Several related white papers are linked [[http://tagstore.org/en/papers.shtml][on the tagstore homepage]].

* License

https://github.com/novoid/2011-01-tagstore-formal-experiment is
licensed under a [[http://creativecommons.org/licenses/by-nc-sa/3.0/][Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License]].

* What is missing

For now, all relevant experiment data is online. If something is not
online (like for example the TP videos), a README.org explains further
things or links to an alternative hosting place.

Currently, the detailed results are being extracted. The raw results
are somewhat irritating due to several things like bugs in
software. 

Here is the list of things which will be published here in future:

** Transcript processing scripts

Python-parser are reading the transcript files and generate a ASCII
and CSV summary per transcript file. Those parsers will be published
too.

** Summarized Results

The raw summary CSV files (all TPs) are committed already. The
spreadsheets containing the derived diagrams will be published soon.

** Formal Experiment Report

A report containing the most important results will be published here.

