* Formal Experiment

In January 2011, a formal experiment was conducted which aimed to
clear some questions in the field of personal information management
(PIM), information re-finding, and information architecture.

For this purpose, the testing framework [[http://tagstore.org][tagstore]] was used to *compare*
storing files (images, graphics and documents) within the 
*folder hierarchy* using Microsoft Windows Explorer *and tagstore*.

The tagstore framework supports file management by applying
tags. Those tags are being used to (automatically) generate *navigation
hierarchies*, called TagTrees.

This repository contains anonymous data from the experiment in order
to *check, extend, or re-evaluate the experiment*. This is Open Data,
this is Open Science.

* Language

The experiment took place in Graz, Austria. Therefore, the language of
the test persons was *German*. All data which test persons were
confronted with is in German. Derived data and other things such as
evaluation scripts are in *English* though.

* White Papers

Several related white papers are linked [[http://tagstore.ist.tugraz.at/en/papers][on the tagstore homepage]].

* What is missing

For now, each relevant experiment data is online. If something is not
online (like for example the TP videos), a README.org explains further
things or links to an alternative hosting place.

Currently, the detailed results are being extracted. The raw results
are somewhat irritating due to several things like bugs in
software. 

Here is the list of things which will be published here in future:

** Transcripts

We developed a detailed transcript language and are writing down each
event very carefully: counting mouse clicks, writing down each spoken
word, taking notes on each relevant GUI element interaction. 

This took us very long.

The definition of the transcript language will be published here
too.

The raw transcript files will be published here soon.

** Transcript processing scripts

Python-parser are reading the transcript files and generate a ASCII
and CSV summary per transcript file. Those parsers will be published
too.

** Raw and Summarized Results

The summarized CSV files (all TPs) as well as Spreadsheets containing
the derived diagrams will be published.

** Formal Experiment Report

A report containing the most important results will be published here.

